version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=file:///app/mlruns
    volumes:
      - ./mlruns:/app/mlruns
      - ./artifacts:/app/artifacts

