artifact_location: file:///Users/adityaswaroop/Downloads/MLOps-End-To-End-Project-master/mlruns_local/0/models/m-3d1eb12d7f064930a3ce5c2581451897/artifacts
creation_timestamp: 1755059014261
experiment_id: '0'
last_updated_timestamp: 1755059017371
model_id: m-3d1eb12d7f064930a3ce5c2581451897
model_type: null
name: model
source_run_id: 1a550ffe02ab418c918b16ad62224c6d
status: 2
status_message: null
