artifact_location: file:///Users/adityaswaroop/Downloads/MLOps-End-To-End-Project-master/mlruns_local/0
creation_time: 1755057874139
experiment_id: '0'
last_update_time: 1755057874139
lifecycle_stage: active
name: Default
