artifact_uri: file:///Users/adityaswaroop/Downloads/MLOps-End-To-End-Project-master/mlruns_local/0/324648c4204d45dba148b041ce938320/artifacts
end_time: 1755057876031
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 324648c4204d45dba148b041ce938320
run_name: upbeat-bird-61
source_name: ''
source_type: 4
source_version: ''
start_time: 1755057874196
status: 3
tags: []
user_id: adityaswaroop
